In [2]:
import numpy as np

In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3,4,5,6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [9]:
np.zeros((4))

array([0., 0., 0., 0.])

In [10]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((4))

array([1., 1., 1., 1.])

In [13]:
np.empty((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.empty((4))

array([1., 1., 1., 1.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [25]:
# Reshape array
a.reshape((2, 3))


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:

# Flatten array
a.flatten()


array([1, 2, 3, 4, 5, 6])

In [27]:

# Transpose array
b = np.array([[1, 2], [3, 4]])
b.T


array([[1, 3],
       [2, 4]])

In [28]:

# Concatenate arrays
b = np.array([7,8,9,10,11,12])
np.concatenate((a,b))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:

# Unique elements
numbers = np.array([1,5,3,1,4,5,6,7,3])
np.unique(numbers)

array([1, 3, 4, 5, 6, 7])

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])



In [3]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([[5, 6, 7 ],[8, 9, 10]])

In [7]:
arr2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [9]:
np.mean(arr)

np.float64(3.0)

In [10]:
np.mean(arr2)

np.float64(7.5)

In [12]:
np.std(arr)

np.float64(1.4142135623730951)

In [13]:
np.std(arr2)

np.float64(1.707825127659933)

In [18]:
arr3 = np.array([30, 40, 50,90]) 

In [19]:
arr3

array([30, 40, 50, 90])

In [20]:
np.std(arr3)

np.float64(22.776083947860748)

In [21]:
np.var(arr3)

np.float64(518.75)

In [22]:
np.percentile(arr3, 50)

np.float64(45.0)

In [23]:
np.percentile(arr3, 0)

np.float64(30.0)

In [24]:
np.percentile(arr3, 100)

np.float64(90.0)

In [31]:
# Base-10 logarithm of elements
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897   ]


In [26]:
# Sum of elements
print(np.sum(arr))


15


In [27]:

# Sum of elements along an axis (for multi-dimensional arrays)
print(np.sum(arr2, axis=0))  # Sum along columns
print(np.sum(arr2, axis=1))  # Sum along rows

[13 15 17]
[18 27]


In [28]:


# Product of elements
print(np.prod(arr))


120


In [29]:

# Cumulative sum of elements
print(np.cumsum(arr))

[ 1  3  6 10 15]


In [30]:
# Exponential of all elements
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [32]:
# Natural logarithm of elements
print(np.log(arr))


[0.         0.69314718 1.09861229 1.38629436 1.60943791]
