In [2]:
import numpy as np

In [3]:
import numpy as np

In [5]:
a = np.array([1, 2, 3,4,5,6])

In [6]:
a

array([1, 2, 3, 4, 5, 6])

In [9]:
np.zeros((4))

array([0., 0., 0., 0.])

In [10]:
np.zeros((4, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((4))

array([1., 1., 1., 1.])

In [13]:
np.empty((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.empty((4))

array([1., 1., 1., 1.])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.eye(4, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [25]:
# Reshape array
a.reshape((2, 3))


array([[1, 2, 3],
       [4, 5, 6]])

In [26]:

# Flatten array
a.flatten()


array([1, 2, 3, 4, 5, 6])

In [27]:

# Transpose array
b = np.array([[1, 2], [3, 4]])
b.T


array([[1, 3],
       [2, 4]])

In [28]:

# Concatenate arrays
b = np.array([7,8,9,10,11,12])
np.concatenate((a,b))


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:

# Unique elements
numbers = np.array([1,5,3,1,4,5,6,7,3])
np.unique(numbers)

array([1, 3, 4, 5, 6, 7])